#!/usr/bin/env -S python2 -u

#setvar( "GameOptions.GameInfo.LevelName", "CastleStrike.lxl" )

setvar( "GameOptions.GameInfo.ModName", "MW 1.0" )

setvar( "GameOptions.GameInfo.LoadingTime", "20" )

SetWeaponBans("Mortar Only")
