# Single source of truth for the in-binary OLX version.
#
# Generates a Version_generated.h that defines LX_VERSION from the output of
# get_version_full.sh (see functions.sh:get_olx_version_with_hash — the
# YYYYMMDD.N+git.HASH scheme). The binary embeds the full version (with hash)
# for provenance/crash reports; the menu and window title display the short
# version via GetGameVersionShortString(). src/common/Version.cpp is the only
# translation unit that includes Version_generated.h, so bumping the version
# recompiles just that one file.
#
# Without this Version.cpp has no LX_VERSION and the build fails (#error)
# rather than baking in a bogus version.
#
# Usage (from any of the per-platform CMake builds):
#   include(${OLX_SOURCE_ROOT}/CMakeOlxVersion.cmake)
#   olx_generate_version_header(${OLX_SOURCE_ROOT} OLX_VERSION_INCLUDE_DIR)
#   # then add OLX_VERSION_INCLUDE_DIR to the include path *before* include/
#   # so the generated header wins over the empty include/Version_generated.h
#   # stub, e.g.:
#   target_include_directories(<tgt> BEFORE PRIVATE ${OLX_VERSION_INCLUDE_DIR})
#   # or, for directory-scoped builds:
#   INCLUDE_DIRECTORIES(BEFORE ${OLX_VERSION_INCLUDE_DIR})

macro(olx_generate_version_header OLX_SRC_ROOT OUT_VAR)
	execute_process(
		COMMAND sh "${OLX_SRC_ROOT}/get_version_full.sh"
		OUTPUT_VARIABLE _olx_ver
		OUTPUT_STRIP_TRAILING_WHITESPACE
		RESULT_VARIABLE _olx_ver_rc
		ERROR_VARIABLE _olx_ver_err)
	if(NOT _olx_ver_rc EQUAL 0 OR _olx_ver STREQUAL "")
		message(FATAL_ERROR
			"Could not determine the OLX version via get_version_full.sh "
			"(exit ${_olx_ver_rc}): ${_olx_ver_err}"
			"Refusing to build without a real version.")
	endif()
	message(STATUS "OLX_VERSION = ${_olx_ver}")

	set(_olx_gen_dir "${CMAKE_BINARY_DIR}/olx-version-include")
	set(_olx_hdr "${_olx_gen_dir}/Version_generated.h")
	set(_olx_content "/* Auto-generated by CMakeOlxVersion.cmake -- do not edit.\n   Single source of truth: get_version_full.sh (functions.sh:get_olx_version_with_hash). */\n#define LX_VERSION \"${_olx_ver}\"\n")

	# Only rewrite when the content actually changes, otherwise every cmake
	# re-run would force a Version.cpp recompile.
	set(_olx_old "")
	if(EXISTS "${_olx_hdr}")
		file(READ "${_olx_hdr}" _olx_old)
	endif()
	if(NOT _olx_old STREQUAL _olx_content)
		file(WRITE "${_olx_hdr}" "${_olx_content}")
	endif()

	set(${OUT_VAR} "${_olx_gen_dir}")
endmacro()
