name: Flatpak

on:
  pull_request:
  push:
    branches:
      - 0.59
  workflow_dispatch:

jobs:
  flatpak-builder:
    name: Build Flatpak bundle
    runs-on: ubuntu-24.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: openlierox.flatpak
          manifest-path: flatpak/net.openlierox.OpenLieroX.yaml
          cache-key: flatpak-builder-${{ github.sha }}
